//Esta función recibe el parametro client, message, y args para ser usados:
  const Discord = require("discord.js") //Definimos Discord.
module.exports = async(client, message, args) => { 


 const embed = new Discord.MessageEmbed()
 .setTitle("")
       .setImage("https://cdn.discordapp.com/attachments/807679992695488523/809630782939332618/embed1.jpg")
message.channel.send(embed)
 const embed1 = new Discord.MessageEmbed()
.setTitle("¿Qué puedo hacer dentro del servidor?")
 .setDescription(`> Aquí intentamos ofrecer una experiencia de rol "única", con esto me refiero a despegarnos del clásico estilo de ciudad el cúal se puede ver en cada rol, de esta forma cambiar el entorno, cambiar las reglas y crear un espacio en el cualquier rol tenga cavida es nuestro principal objetivo para este servidor. \n Empezarás en un ambiente totalmente desconocido, en el que valerte por ti mismo será tu mayor problema durante la escasez de recursos.`)
  message.channel.send(embed1)
 const embed2 = new Discord.MessageEmbed()
 .setTitle(`Explora..`)
 .setDescription(`Empezarás en un ambiente totalmente distinto en el que tendrás que abrirte paso por tus propios medios, un mapa será tu mejor amigo, la civilización tuvo que volver a empezar, por lo que será dificíl guiarte por estos terrenos tú sólo.`)
 .setImage('https://cdn.discordapp.com/attachments/807679992695488523/808852755745079327/unknown.png')
 message.channel.send(embed2)
 const embed3 = new Discord.MessageEmbed()
 .setTitle(`Recolecta recursos`)
 .setDescription(`En el medio del bosque necesitarás recolectar los recursos que la tierra te ofrece para poder sobrevivir, tendrás que tirar abajo innumerables arboles para construirte un refugio, picar miles de piedras para venderlas o intercambiarlas por bienes con otros jugadores aunque estas se consideran de gran valor debido a su escasez.`)
 .setImage('https://cdn.discordapp.com/attachments/807679992695488523/809639828072431627/ezgif.com-gif-maker.gif')
 message.channel.send(embed3)
   const embed4 = new Discord.MessageEmbed()
 .setImage('https://cdn.discordapp.com/attachments/807679992695488523/809642013476519996/ezgif.com-gif-maker_1.gif')
 message.channel.send(embed4)
     const embed5 = new Discord.MessageEmbed()
     .setTitle('Caza')
     .setDescription('Aventurate dentro del bosque para cazar distintos tipos de animales, mayormente pasivos, pero siempre ten un ojo abierto, hay criaturas que no te la dejarán tan facil, que lucharan por su vida y por acabar la tuya\n Recuerda que distintos tipos de animales sueltan distintas pieles y estas mismas se venden por distintos precios')
 .setImage('https://cdn.discordapp.com/attachments/807679992695488523/809876350537039932/ezgif.com-gif-maker_2.gif')
 message.channel.send(embed5)
     const embed6 = new Discord.MessageEmbed()
     .setImage('https://cdn.discordapp.com/attachments/807679992695488523/809876814335967242/Unturned_en_GeForce_NOW_10_2_2021_1_04_11.png')
 message.channel.send(embed6)
       const embed7 = new Discord.MessageEmbed()
       .setTitle('Hazte de amigos')
     .setDescription('A duras penas podrás valerte por tí mismo en este ambiente, por el camino irás haciendote de amistades y buenos amigos que siempre estarán para tí cuando los necesites')
 .setImage('https://cdn.discordapp.com/attachments/807679992695488523/809879152143892480/Unturned_en_GeForce_NOW_12_2_2021_4_00_45.png')
   message.channel.send(embed7)
       const embed8 = new Discord.MessageEmbed()
      .setImage('https://cdn.discordapp.com/attachments/807679992695488523/809882895027404880/ezgif.com-gif-maker_3.gif')
          message.channel.send(embed8)
  const embed9 = new Discord.MessageEmbed()
        .setTitle('Conforma un grupo')
     .setDescription('Con el paso del tiempo irás conformando amistades y será hora de crear un grupo, tener su propia base, salir a recoger recursos en grupo, expediciones de caza o enfrentarse a otros grupos.')
 .setImage('https://cdn.discordapp.com/attachments/807679992695488523/809884551404847154/unknown.png')
   message.channel.send(embed9)
        const embed10 = new Discord.MessageEmbed()
  .setImage('https://cdn.discordapp.com/attachments/807679992695488523/809884623466135552/unknown.png')
   message.channel.send(embed10)

  } 